  <TableChart
    title={dashboardData.tableCharts.topAlarmDispatchDetail.title}
    data={dashboardData.tableCharts.topAlarmDispatchDetail.data}
    columns={dashboardData.tableCharts.topAlarmDispatchDetail.columns}
  />
  <TableChart
    title={dashboardData.tableCharts.topAlarmAlertResponseByRecipientDetail.title}
    data={dashboardData.tableCharts.topAlarmAlertResponseByRecipientDetail.data}
    columns={dashboardData.tableCharts.topAlarmAlertResponseByRecipientDetail.columns}
  />
  <TableChart
    title={dashboardData.tableCharts.topAlarmAlertResponseDetail.title}
    data={dashboardData.tableCharts.topAlarmAlertResponseDetail.data}
    columns={dashboardData.tableCharts.topAlarmAlertResponseDetail.columns}
  /> 